[#rancher-installation-quickstart]
= Installing {ranchermanager} on a {kube} cluster

In this section, you will learn how to deploy {ranchermanager} on a {k8s} cluster using the {helm} CLI.

[#rancher-prerequisites]
== Prerequisites

* xref:rancher-k8s-cluster[{k8s} cluster]
* xref:rancher-ingress-controller[{ingress} controller]
* xref:rancher-cli-tools[CLI tools]

[#rancher-k8s-cluster]
=== {k8s} cluster

Set up the {ranchermanager} server's local {k8s} cluster.

{ranchermanager} can be installed on any {k8s} cluster.
This cluster can use upstream {k8s}, or it can use one of {ranchermanager}'s {k8s} distributions, or it can be a managed {k8s} cluster from a provider such as Amazon EKS.

[TIP]
====
ifdef::deployment_standard[]
For help setting up a {rke2a} cluster, refer to xref:rke2-installation-quickstart[].
endif::[]
ifdef::deployment_airgap[]
For help setting up a {rke2a} cluster, refer to xref:rke2-installation-airgapped[].
endif::[]
====

[#rancher-ingress-controller]
=== {ingress} controller

The {ranchermanager} UI and API are exposed through an {ingress}.
This means the {k8s} cluster that you install {ranchermanager} in must contain an {ingress} controller.

For {rke2} and K3s installations, you do not have to install the {ingress} controller manually because one is installed by default.

[#rancher-cli-tools]
=== CLI tools

The following CLI tools are required for setting up the {k8s} cluster.
Make sure these tools are installed and available in your `$PATH`.

* link:https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl[`kubectl`] - {k8s} command-line tool.
* link:https://docs.helm.sh/using_helm/#installing-helm[`helm`] - Package management for {k8s}.
Refer to the link:https://docs.ranchermanager.rancher.io/getting-started/installation-and-upgrade/requirements/helm-version-requirements[{helm} version requirements] to choose a version of {helm} to install {ranchermanager}.
Refer to the link:https://helm.sh/docs/intro/install/[instructions provided by the {helm} project] for your specific platform.

[#rancher-install-helm-chart]
== Install the {ranchera} {helm} chart

{ranchermanager} is installed using the link:https://helm.sh/[{helm}] package manager for {k8s}.
{helm} charts provide templating syntax for {k8s} YAML manifest documents.
With {helm}, we can create configurable deployments instead of just using static files.

To choose a {ranchermanager} version to install, refer to link:https://docs.ranchermanager.rancher.io/getting-started/installation-and-upgrade/resources/choose-a-rancher-version[Choosing a {ranchermanager} version].

To choose a version of {helm} to install {ranchermanager} with, refer to the link:https://docs.ranchermanager.rancher.io/getting-started/installation-and-upgrade/requirements/helm-version-requirements[{helm} version requirements].

[NOTE]
====
The installation instructions assume you are using {helm} version 3.
====

To set up {ranchermanager},

. xref:rancher-add-helm-repo[Add the {helm} chart repository]
. xref:rancher-create-namespace[Create a namespace for {ranchera}]
. xref:rancher-choose-ssl[Choose your SSL configuration]
. xref:rancher-install-cert-manager[Install {certmanager}]
. xref:rancher-install-with-helm[Install {ranchera} with {helm} and your chosen certificate option]
. xref:rancher-verify-deployment[Verify that the {ranchera} server is successfully deployed]
. xref:rancher-save-options[Save your options]

[#rancher-add-helm-repo]
== Add the {helm} chart repository

Use the `helm repo add` command to add the {helm} chart repository that contains charts to install {rancherprime}.

[source,bash,subs="+attributes"]
----
{prompt_user}helm repo add rancher-prime <helm-chart-repo-url>
----

For information on the {helm} chart repository URL, refer to the {rancherprime} documentation.

[#rancher-create-namespace]
== Create a namespace for {ranchera}

Define a {k8s} namespace where the resources created by the chart will be installed named `cattle-system`:

[source,bash,subs="+attributes"]
----
{prompt_user}kubectl create namespace cattle-system
----

[#rancher-choose-ssl]
== Choose your SSL configuration

The {ranchermanager} management server is designed to be secure by default and requires SSL/TLS configuration.

[NOTE]
====
To externally cancel SSL/TLS, see link:https://docs.ranchermanager.rancher.io/getting-started/installation-and-upgrade/references/helm-chart-options#external-tls-termination[TLS termination on an External Load Balancer].
As outlined on that page, this option does have additional requirements for TLS verification.
====

There are three recommended options for the source of the certificate used for TLS termination at the {ranchermanager} server:

* *{ranchermanager}-generated TLS certificate:* In this case, you need to install `cert-manager` into the cluster.
{ranchermanager} utilizes `cert-manager` to issue and maintain its certificates.
{ranchermanager} generates a CA certificate of its own, and sign a certificate using that CA.
`cert-manager` is then responsible for managing that certificate.
No extra action is needed when `agent-tls-mode` is set to strict.
More information can be found on this setting in link:https://docs.ranchermanager.rancher.io/getting-started/installation-and-upgrade/references/tls-settings#agent-tls-enforcement[Agent TLS Enforcement].
* *Let's Encrypt:* The Let's Encrypt option also uses `cert-manager`.
However, in this case, {certmanager} is combined with a special Issuer for Let's Encrypt that performs all actions (including request and validation) necessary for getting a Let's Encrypt issued cert.
This configuration uses HTTP validation (`HTTP-01`), so the load balancer must have a public DNS record and be accessible from the internet.
When setting `agent-tls-mode` to `strict`, you must also specify `--privateCA=true` and upload the Let's Encrypt CA as described in link:https://docs.ranchermanager.rancher.io/getting-started/installation-and-upgrade/resources/tls-secrets[Adding TLS Secrets].
Find more information on this setting in link:https://docs.ranchermanager.rancher.io/getting-started/installation-and-upgrade/references/tls-settings#agent-tls-enforcement[Agent TLS Enforcement].
* *Bring your own certificate:* This option allows you to bring your own public- or private-CA signed certificate.
{ranchermanager} will use that certificate to secure websocket and HTTPS traffic.
In this case, you must upload this certificate (and associated key) as PEM-encoded files with the name `tls.crt` and `tls.key`.
If you are using a private CA, you must also upload that certificate.
This is because this private CA may not be trusted by your nodes.
{ranchermanager} will take that CA certificate, and generate a checksum from it, which the various {ranchermanager} components use to validate their connection to {ranchermanager}.
If `agent-tls-mode` is set to `strict`, the CA must be uploaded, so that downstream clusters can successfully connect.
Find more information in link:https://docs.ranchermanager.rancher.io/getting-started/installation-and-upgrade/references/tls-settings#agent-tls-enforcement[Agent TLS Enforcement].

.SSL Configuration Options
[cols="3"]
|===
|Configuration |{helm} Chart Option |Requires {certmanager}

|{ranchermanager} Generated Certificates (Default)
|`ingress.tls.source=rancher`
|xref:rancher-install-cert-manager[yes]

|Let's Encrypt
|`ingress.tls.source=letsEncrypt`
|xref:rancher-install-cert-manager[]

|Certificates from Files
|`ingress.tls.source=secret`
|no
|===

[#rancher-install-cert-manager]
== Install {certmanager}

You should skip this step if you are bringing your own certificate files (option `ingress.tls.source=secret`), or if you use link:https://docs.ranchermanager.rancher.io/getting-started/installation-and-upgrade/references/helm-chart-options#external-tls-termination[TLS termination on an external load balancer].

This step is only required to use certificates issued by {ranchermanager}'s generated CA (`ingress.tls.source=rancher`) or to request Let's Encrypt issued certificates (`ingress.tls.source=letsEncrypt`).

[IMPORTANT]
====
Recent changes to {certmanager} require an upgrade.
If you are upgrading {ranchermanager} and using a version of {certmanager} older than v0.11.0, please see our link:https://docs.ranchermanager.rancher.io/getting-started/installation-and-upgrade/resources/upgrade-cert-manager[upgrade documentation].
====

These instructions are adapted from the link:https://cert-manager.io/docs/installation/kubernetes/#installing-with-helm[official {certmanager} documentation].

[NOTE]
====
To see options on how to customize the {certmanager} install including for cases where your cluster uses PodSecurityPolicies, see the link:https://artifacthub.io/packages/helm/cert-manager/cert-manager#configuration[cert-manager docs].
====

[source,bash]
----
# If you have installed the CRDs manually, instead of setting --set installCRDs=true \
  or --set crds.enabled=true in your Helm install command, \
  you should upgrade your CRD resources before upgrading the Helm chart:
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/<VERSION>/cert-manager.crds.yaml

# Add the Jetstack Helm repository
helm repo add jetstack https://charts.jetstack.io

# Update your local Helm chart repository cache
helm repo update

# Install the cert-manager Helm chart
helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --set crds.enabled=true
----

Once you have installed {certmanager}, you can verify it is deployed correctly by checking the {certmanager} namespace for running pods:

[source]
----
kubectl get pods --namespace cert-manager

NAME                                       READY   STATUS    RESTARTS   AGE
cert-manager-5c6866597-zw7kh               1/1     Running   0          2m
cert-manager-cainjector-577f6d9fd7-tr77l   1/1     Running   0          2m
cert-manager-webhook-787858fcdb-nlzsq      1/1     Running   0          2m
----

[#rancher-install-with-helm]
== Install {ranchera} with {helm} and your chosen certificate option

The exact command to install {ranchermanager} differs depending on the certificate configuration.

However, irrespective of the certificate configuration, the name of the {ranchermanager} installation in the `cattle-system` namespace should always be `rancher`.

[TIP]
====
.Testing and development
This final command to install {ranchermanager} requires a domain name that forwards traffic to {ranchermanager}.
If you are using the {helm} CLI to set up a proof-of-concept, you can use a fake domain name when passing the `hostname` option.
An example of a fake domain name would be `<IP_OF_LINUX_NODE>.sslip.io`, which would expose {ranchermanager} on an IP where it is running.
Production installs would require a real domain name.
====

[#rancher-generated-certs]
=== {ranchera}-generated certificates

The default is for {ranchermanager} to generate a CA and uses `cert-manager` to issue the certificate for access to the {ranchermanager} server interface.

Because `rancher` is the default option for `ingress.tls.source`, we are not specifying `ingress.tls.source` when running the `helm install` command.

* Set the `hostname` to the DNS name you pointed at your load balancer.
* Set the `bootstrapPassword` to something unique for the `admin` user.
* To install a specific {ranchermanager} version, use the `--version` flag, example: `--version 2.7.0`

[source,bash,subs="+attributes"]
----
{prompt_user}helm install rancher rancher-prime/rancher \
  --namespace cattle-system \
  --set hostname=rancher.my.org \
  --set bootstrapPassword=admin
----

Wait for {ranchermanager} to be rolled out:

[source,bash,subs="+attributes"]
----
{prompt_user}kubectl -n cattle-system rollout status deploy/rancher
Waiting for deployment "rancher" rollout to finish: 0 of 3 updated replicas are available...
deployment "rancher" successfully rolled out
----

[#rancher-lets-encrypt]
=== Let's Encrypt

This option uses `cert-manager` to automatically request and renew link:https://letsencrypt.org/[Let's Encrypt certificates].
This is a free service that provides you with a valid certificate as Let's Encrypt is a trusted CA.

[NOTE]
====
You need to have port 80 open as the HTTP-01 challenge can only be done on port 80.
====

In the following command,

* `hostname` is set to the public DNS record,
* Set the `bootstrapPassword` to something unique for the `admin` user.
* `ingress.tls.source` is set to `letsEncrypt`
* `letsEncrypt.email` is set to the email address used for communication about your certificate (for example, expiry notices)
* Set `letsEncrypt.ingress.class` to whatever your {ingress} controller is, for example, `traefik`, `nginx`, `haproxy`, etc.

[IMPORTANT]
====
When `agent-tls-mode` is set to `strict` (the default value for new installs of {ranchermanager} starting from v2.9.0), you must supply the `privateCA=true` chart value (e.x. through `--set privateCA=true`) and upload the Let's Encrypt Certificate Authority as outlined in link:https://docs.ranchermanager.rancher.io/getting-started/installation-and-upgrade/resources/tls-secrets[Adding TLS Secrets].
Information on identifying the Let's Encrypt Root CA can be found in the Let's Encrypt link:https://letsencrypt.org/certificates/[docs].
If you do not upload the CA, then {ranchermanager} may fail to connect to new or existing downstream clusters.
====

[source,bash,subs="+attributes"]
----
{prompt_user}helm install rancher rancher-prime/rancher \
  --namespace cattle-system \
  --set hostname=rancher.my.org \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=me@example.org \
  --set letsEncrypt.ingress.class=nginx
----

Wait for {ranchermanager} to be rolled out:

[source,bash,subs="+attributes"]
----
{prompt_user}kubectl -n cattle-system rollout status deploy/rancher
Waiting for deployment "rancher" rollout to finish: 0 of 3 updated replicas are available...
deployment "rancher" successfully rolled out
----

[#rancher-certs-from-files]
=== Certificates from files

In this option, {k8s} secrets are created from your own certificates for {ranchermanager} to use.

When you run this command, the `hostname` option must match the `Common Name` or a `Subject Alternative Names` entry in the server certificate or the {ingress} controller will fail to configure correctly.

Although an entry in the `Subject Alternative Names` is technically required, having a matching `Common Name` maximizes compatibility with older browsers and applications.

[NOTE]
====
To check if your certificates are correct, see link:https://docs.ranchermanager.rancher.io/faq/technical-items#how-do-i-check-common-name-and-subject-alternative-names-in-my-server-certificate[How do I check Common Name and Subject Alternative Names in my server certificate?]
====

* Set the `hostname`.
* Set the `bootstrapPassword` to something unique for the `admin` user.
* Set `ingress.tls.source` to `secret`.

[source,bash,subs="+attributes"]
----
{prompt_user}helm install rancher rancher-prime/rancher \
  --namespace cattle-system \
  --set hostname=rancher.my.org \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=secret
----

If you are using a Private CA signed certificate , add `--set privateCA=true` to the command:

[source,bash,subs="+attributes"]
----
{prompt_user}helm install rancher rancher-prime/rancher \
  --namespace cattle-system \
  --set hostname=rancher.my.org \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=secret \
  --set privateCA=true
----

Now that {ranchermanager} is deployed, see link:https://docs.ranchermanager.rancher.io/getting-started/installation-and-upgrade/resources/tls-secrets[Adding TLS Secrets to publish the certificate files so {ranchermanager} and the {ingress} controller can use them].

[#rancher-advanced-options]
=== Advanced options

The {ranchermanager} chart configuration has many options for customizing the installation to suit your specific environment.
Here are common advanced scenarios.

* link:https://docs.ranchermanager.rancher.io/getting-started/installation-and-upgrade/references/helm-chart-options#http-proxy[HTTP Proxy]
* link:https://docs.ranchermanager.rancher.io/getting-started/installation-and-upgrade/references/helm-chart-options#private-registry-and-air-gap-installs[Private Container Image Registry]
* link:https://docs.ranchermanager.rancher.io/getting-started/installation-and-upgrade/references/helm-chart-options#external-tls-termination[TLS Termination on an External Load Balancer]

See the link:https://docs.ranchermanager.rancher.io/getting-started/installation-and-upgrade/references/helm-chart-options[Chart Options] for the full list of options.

[#rancher-verify-deployment]
== Verify that the {ranchera} server is successfully deployed

After adding the secrets, check if {ranchermanager} was rolled out successfully:

[source,bash,subs="+attributes"]
----
{prompt_user}kubectl -n cattle-system rollout status deploy/rancher
Waiting for deployment "rancher" rollout to finish: 0 of 3 updated replicas are available...
deployment "rancher" successfully rolled out
----

If you see the following error: `error: deployment "rancher" exceeded its progress deadline`, you can check the status of the deployment by running the following command:

[source,bash,subs="+attributes"]
----
{prompt_user}kubectl -n cattle-system get deploy rancher
NAME      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
rancher   3         3         3            3           3m
----

It should show the same count for `DESIRED` and `AVAILABLE`.

[#rancher-save-options]
== Save your options

Make sure you save the `--set` options you used.
You will need to use the same options when you upgrade {ranchermanager} to new versions with {helm}.

[#rancher-finishing-up]
== Finishing up

Now you should have a functional {ranchermanager} server.

In a Web browser, go to the DNS name that forwards traffic to your load balancer.
Then you should be greeted by the colorful login page.
