[#ai-requirements-ollama]
= {ollama} requirements

The version of {ollama} provided with {productname} is optimized for {nvidia} GPU hardware. This section guides you through the steps for configuring {ollama} on an {nvidia}-enabled system, including necessary configurations for both the hardware and software.

[TIP]
.General recommendations
====
* *Run {ollama} on {nvidia} GPU nodes.*
Since {ollama} is GPU-optimized, using the power of {nvidia} GPUs is essential for maximum performance. This ensures that the application runs efficiently and fully uses the hardware capabilities.
* *Assign applications to specific nodes.*
{productname} provides a mechanism to assign applications, such as {ollama}, to specific nodes. For more details, refer to {dsc}/suse-ai/1.0/html/AI-deployment-intro/index.html#ai-gpu-nodes-assigning[].
====

[#ai-reqs-ollama-hw]
== Hardware requirements

[role="tabs"]
{nvidia} GPU::
* The recommended GPU models include Tesla, A100, V100, RTX 30 series, or other compatible {nvidia} GPUs.
* Ensure that the CUDA Compute Capability of your GPU is compatible with the required version of {ollama}.
RAM:: At least 16{nbsp}GB of RAM is recommended. However, higher amounts (32{nbsp}GB or more) may be necessary for larger models or workloads.
Disk space:: At least 50{nbsp}GB of free disk space is recommended for storing the container images and any data files processed by {ollama}.

[#ai-reqs-ollama-sw]
== Software requirements

{nvidia} {docker} (nvidia-docker):: You must install `nvidia-docker` (the {nvidia} Container Toolkit) to allow {docker} containers to use the GPU. Refer to {dsc}/cloudnative/rke2/latest/en/advanced.html#_deploy_nvidia_operator[] for more details.
CUDA Toolkit:: You must install the CUDA version supported by your GPU model. For most recent GPUs, CUDA 11.0 or later is required. Refer to https://developer.nvidia.com/cuda-toolkit[CUDA Toolkit installation guide] for more details.
{nvidia} driver::
Install the {nvidia} driver compatible with your GPU model. Its version must be compatible with the installed CUDA toolkit.
+
[TIP]
--
You can check your GPU driver version by running the `nvidia-smi` command.
--
